/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atividade.pkg1.da.lista.pkg3;

import javax.swing.JOptionPane;

/**
 *
 * @author 04474667042
 */
public class Interface01 extends javax.swing.JFrame {

    /**
     * Creates new form Interface01
     */
    public Interface01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Jupter = new javax.swing.JRadioButton();
        Mercurio = new javax.swing.JRadioButton();
        Marte = new javax.swing.JRadioButton();
        Saturn = new javax.swing.JRadioButton();
        Urano = new javax.swing.JRadioButton();
        Venus = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        pesotxtf = new javax.swing.JTextField();
        CalcularButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(Jupter);
        Jupter.setText("Jupter");
        Jupter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JupterActionPerformed(evt);
            }
        });

        buttonGroup1.add(Mercurio);
        Mercurio.setText("Mercurio");
        Mercurio.setActionCommand("Mercurio");
        Mercurio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MercurioActionPerformed(evt);
            }
        });

        buttonGroup1.add(Marte);
        Marte.setText("Marte");
        Marte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarteActionPerformed(evt);
            }
        });

        buttonGroup1.add(Saturn);
        Saturn.setText("Saturno");
        Saturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaturnActionPerformed(evt);
            }
        });

        buttonGroup1.add(Urano);
        Urano.setText("Urano");
        Urano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UranoActionPerformed(evt);
            }
        });

        buttonGroup1.add(Venus);
        Venus.setText("Venus");
        Venus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VenusActionPerformed(evt);
            }
        });

        jLabel1.setText("O Peso aqui:");

        pesotxtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesotxtfActionPerformed(evt);
            }
        });

        CalcularButton.setText("Calcular Peso");
        CalcularButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Selecione o planeta abaixo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Mercurio)
                            .addComponent(Jupter))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Saturn)
                            .addComponent(Venus))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Urano)
                            .addComponent(Marte)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pesotxtf, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CalcularButton))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesotxtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CalcularButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mercurio)
                    .addComponent(Venus)
                    .addComponent(Marte))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jupter)
                    .addComponent(Saturn)
                    .addComponent(Urano))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JupterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JupterActionPerformed
        
    }//GEN-LAST:event_JupterActionPerformed

    private void MercurioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MercurioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MercurioActionPerformed

    private void MarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MarteActionPerformed

    private void VenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VenusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VenusActionPerformed

    private void UranoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UranoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UranoActionPerformed

    private void SaturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaturnActionPerformed

    private void CalcularButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularButtonActionPerformed
        String pesoCalc = pesotxtf.getText();
    double pesoC;
    if (Mercurio.isSelected()) {
        double peso = Double.parseDouble(pesoCalc);
        pesoC = peso * 0.37;
        JOptionPane.showMessageDialog(null, "Seu peso em Mercúrio é: " + pesoC + " Kg");
        
    } else if (Venus.isSelected()) {
        double peso = Double.parseDouble(pesoCalc);
        pesoC = peso * 0.88;
        JOptionPane.showMessageDialog(null, "Seu peso em Venus é: " + pesoC + " Kg");
        
    } else if (Marte.isSelected()) {
        double peso = Double.parseDouble(pesoCalc);
        pesoC = peso * 0.38;
        JOptionPane.showMessageDialog(null, "Seu peso em Marte é: " + pesoC + " Kg");
        
    }else if (Jupter.isSelected()) {
        double peso = Double.parseDouble(pesoCalc);
        pesoC = peso * 2.64;
        JOptionPane.showMessageDialog(null, "Seu peso em Jupter é: " + pesoC + " Kg");
        
    }else if (Saturn.isSelected()) {
        double peso = Double.parseDouble(pesoCalc);
        pesoC = peso * 1.15;
        JOptionPane.showMessageDialog(null, "Seu peso em Saturn é: " + pesoC + " Kg");
        
    }else if (Urano.isSelected()) {
        double peso = Double.parseDouble(pesoCalc);
        pesoC = peso * 1.17;
        JOptionPane.showMessageDialog(null, "Seu peso em Urano é: " + pesoC + " Kg");
    }
    }//GEN-LAST:event_CalcularButtonActionPerformed

    private void pesotxtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesotxtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesotxtfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalcularButton;
    private javax.swing.JRadioButton Jupter;
    private javax.swing.JRadioButton Marte;
    private javax.swing.JRadioButton Mercurio;
    private javax.swing.JRadioButton Saturn;
    private javax.swing.JRadioButton Urano;
    private javax.swing.JRadioButton Venus;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField pesotxtf;
    // End of variables declaration//GEN-END:variables
}
